### ISSUE TITLE
Inconsistent PKCS7 padding Android native vs iOS

### ISSUE THREAD

**Issue by mh-** [dint-dev/cryptography#103]
Hi,
First of all thank you for this work, Android accelerated AES is really fast with this library. 

This is my problem:

The Android async AES-CBC encryption/decryption does _not_ add/enforce PKCS7 padding, which is perfect for my use case. 

However, when I build the same code for iOS, PKCS7 padding is added, and when decrypting something with missing PKCS7 padding, it throws, and that's a problem for my use case. 

I think that padding and its enforcement should either be completely removed, or made optional consistently over all platforms.

**Comment by mh-** [comment]
For later reference:

I can use my own modified version by changing the `pubspec.yaml` entries in my Flutter app to: 
```
  cryptography:
    git:
      url: https://github.com/mh-/modified_flutter_cryptography.git
      path: cryptography
  cryptography_flutter:
    git:
      url: https://github.com/mh-/modified_flutter_cryptography.git
      path: cryptography_flutter
```

Once I modify this fork on GitHub, I must do `flutter packages upgrade` so that Flutter does not keep using the same version / commit, which if would do even after `flutter pub cache clean && flutter pub get`.
